### ISSUE TITLE
Issues while testing an AngularJS service

### ISSUE THREAD

**Issue by JackFromGarland** [bbraithwaite/CalculatorKarma#1]
Thank you for putting together this excellent article series. 

Brad, 

I'm trying to follow your tutorial and test an AngularJS service. I've taken your test spec and simply replaced $controller with $service.

When I get to this line: 

var myService = $service('MyService', {...});

I get an error trying to run the test: $service is not a function.

Any idea what I'm missing? I can provide more example code if needed.

**Comment by bbraithwaite** [comment]
Hi,

Do Part 1 and 2 from these articles help?

http://www.bradoncode.com/blog/2015/05/24/ngmock-fundamentals-angularjs-unit-testing/

You need to pass the service you are looking for via the injector by its name e.g. you can lookup 'MyService' like this:

 beforeEach(inject(function(_$controller_, MyService){
    $controller = _$controller_;
   myServiceInstance = MyService;
  }));

**Comment by JackFromGarland** [comment]
Thanks for the reply. I finally figured out that there was no $service counterpart to the $controller mock in ngMock. 

I really appreciate the articles. Yesterday I was able to get jasmine tests going for my angular service and I'm off and running. 

Jack

**Comment by bbraithwaite** [comment]
Your thinking is logical, as normally the confusion comes in the other direction, where people are trying to grab an instance of a controller by its name, not realising there is the extra $controller hoop to jump though. Glad to hear that you are making progress! :+1:
